name: muz_bingo_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  path_provider: ^2.1.5
  hive: 2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  freezed_annotation: 2.4.1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  pdf: ^3.11.3
  gap: ^3.0.1
  another_flushbar: ^1.12.30
  pull_down_button: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.0
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  generate: true
