name: muz_bingo_app
description: "Bingo card generator app built with Flutter."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  path_provider: ^2.1.5
  hive: 2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  freezed_annotation: 2.4.1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  pdf: ^3.11.3
  gap: ^3.0.1
  another_flushbar: ^1.12.30
  pull_down_button: ^0.10.2
  printing: ^5.14.2
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.0
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/default_card_background.png
    - assets/fonts/Roboto-Regular.ttf

flutter_native_splash:
  color: "#EBD2D2"
  image: assets/images/logo_splash.png
  android: true
  ios: true
  android_12:
    image: assets/images/logo_splash.png
    icon_background_color: "#FFFFFF"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android_screen_orientation: portrait
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true